### ISSUE TITLE
Too many items in storage system results in disconnect on opening item grid

### ISSUE THREAD

**Issue by tmaaan54** [MelanX/ExtraDisks#25]
#### Issue description:
With over 3 million (estimated) items in storage, server disconnects when item grid is accessed.
#### What happens:
Screen becomes grey, then disconnects with the message "Payload may not be larger than 1048576 bytes"
#### What you expected to happen:
Opening item grid works as normal
#### Steps to reproduce:
1. Have over 3 millions items in storage system (estimated)
2. Attempt to access item/crafting grid

Modpack: All The Mods 6

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5

- Forge: 36.1.2
- Refined Storage: 1.9.12
- Extra disks: 1.5.0

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[latest.log](https://github.com/refinedmods/refinedstorage/files/6217992/latest.log)

Using multiple disks from refined storage or a single disk from extra storage does not appear to make a difference.

**Comment by MelanX** [comment]
Do you have multiple disks? If yes, remove a few ones. And delete items with much nbt data such as different damaged armors and enchanted things. Consider using a filter system to remove them instantly or don't let them in the system.
I can't fix this because it's a vanilla limitation. I hope this fix it for you.
