### ISSUE TITLE
[1.16.5] Crash When Player Joins Server

### ISSUE THREAD

**Issue by HockeyZman2000** [MelanX/ExtraDisks#32]
Hopefully you can tell me what is going on here. When attempting to join the server it immediately crashes with the following log and crash report:

[latest.log](https://github.com/MelanX/ExtraDisks/files/6897380/latest.log)

[crash-2021-07-28_20.37.41-server.txt](https://github.com/MelanX/ExtraDisks/files/6897383/crash-2021-07-28_20.37.41-server.txt)

Some information that I have gathered that might help:

The problem is coming from our storage system which has an infinite disk inside of it, not exactly sure how many items are in it but quite a lot (custom modpack with 181 mods).
Setting the server to remove erroring tile entities completely wipes out the infinite storage disk in the drive.
The logs and report doesn't mention anything about another mod being the cause, so I'm assuming its either this mod or Refined Storage (if the latter is the case I will bring it up with them).

Please help!
I'd like to keep my items :(

**Comment by MelanX** [comment]
You need to re-place the block at position `BlockPos{x=10037, y=127, z=3412}`. The network thinks that there is a network block but there is no network. This causes the server to crash because this is wrong. You could re-create a disk with the command to re-create disks. It's a command added by Refined Storage.
